version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: carsu_db
    environment:
      POSTGRES_USER: carsu
      POSTGRES_PASSWORD: carsu
      POSTGRES_DB: carsu
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carsu -d carsu"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: carsu_api
    environment:
      DATABASE_URL: postgresql://carsu:carsu@db:5432/carsu?schema=public
      JWT_SECRET: dev_jwt_secret_change_me
      PORT: 3000
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '4000:3000'
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: carsu_web
    environment:
      VITE_API_BASE_URL: http://localhost:4000
    depends_on:
      - api
    ports:
      - '5174:5173'
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules

volumes:
  db_data:
